export const CATEGORIES_ADD = "CATEGORIES_ADD"
export const CATEGORIES_SET = "CATEGORIES_SET"
export const CATEGORIES_REMOVE = "CATEGORIES_REMOVE"
export const CATEGORIES_UPDATE = "CATEGORIES_UPDATE"
